#!/bin/bash
# Run cvewatch-agent now. Extra args go to the agent (try --help).
exec sudo podman run --rm --name cvewatch-manual --network host --env-file /opt/labagents/labagents.env \
  -v /opt/labagents/data:/data:z localhost/labagents:latest labagents.cvewatch "$@"
